src/Linter.php
之前 $newCache 只有在检测文件后才会加入
于是原本使用 cache 跳过了检测的文件不会被写入 $newCache 中
导致缓存实际上只能使用一次
=> [Fix] the bug that `.phplint-cache` has been used only once.

src/Command/LintCommand.php
It was added [here](https://github.com/overtrue/phplint/commit/6035c41450d01b4a5af2a5183d0e6a8ee48d07fc#diff-b00b7dcda108d6349dea295226332191R306) and `$fileDescriptor` was never defined.
It raises a warning:
```
PHP Notice:  Undefined variable: fileDescriptor in /var/www/awesome-application/vendor/overtrue/phplint/src/Command/LintCommand.php on line 357
```
when xdebug is set to scream:
```
xdebug.scream = 1
```
=> Removing if condition with undefined variable

README.md, src/Command/LintCommand.php, src/Process/Lint.php
Currently you can only set up the cache file option from the command line, this is because the command is using `$input->getOption('cache')` instead of `$options['cache']`.
With this pull request you can set inside `.phplint.yml` the location of the file just as it was set in the command line. The command line `--cache` argument override the `cache` option from configuration file.
I perform the following test on my machine:
| in config | command line | cache file |
|---|---|---|
| - | - | .phplint-cache |
| .cache-config | - | .cache-config |
| - | .cache-cli | .cache-cli |
| .cache-config | .cache-cli | .cache-cli |
Also in this PR:
- Add --cache=CACHE argument to README.md
- Add `cache: build/phplint.cache` as example inside configuration file to README.md
- Fix doc block: `Method …
=> Feature: set cache option from configuration file

src/Command/LintCommand.php
I am getting the following error when running the CLI command:
```sh
PHP Notice:  Undefined index: cache in /Users/adamplante/projects/project-omega/vendor/overtrue/phplint/src/Command/LintCommand.php on line 157
PHP Stack trace:
PHP   1. {main}() /Users/adamplante/projects/project-omega/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Overtrue\PHPLint\Console\Application->run() /Users/adamplante/projects/project-omega/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Overtrue\PHPLint\Console\Application->doRun() /Users/adamplante/projects/project-omega/vendor/symfony/console/Application.php:143
PHP   4. Overtrue\PHPLint\Console\Application->doRunCommand() /Users/adamplante/projects/project-omega/vendor/symfony/console/Application.php:241
PHP   5. Overtrue\PHPLint\Command\LintCommand->run() …
```
=> Check for non-empty value instead of intrinsic truthy value.

src/Cache.php
This pull request fixes issue #36 
Current behavior of `\Overtrue\PHPLint\Cache::put` is to show a lot of PHP warnings if cannot I/O on the cache file. The class behave in that way on weird cases like: the config file is actually a directory, is not writable, or write on a full disk...
I'm not going to change that, I think we can figure it out how to handle all this I/O FS operations for the whole class in another conversation. You are only using four static methods: `Cache::setFilename`, `Cache::isCached`, `Cache::get()` & `Cache::put()`
My first idea was modify `put` but that is the most used method. Instead I'm working on `setFilename` that is used only once.
When `\Overtrue\PHPLint\Cache::setFilename($filename)` is called the function will check for the directory name of `$filename` …
=> Create folder (recursively) for cache file if it does not exists

composer.json, src/Command/LintCommand.php, src/Linter.php
This pull request contains some improvements found using `php-cs-fixer`, `phpstan`, PhpStorm inspections and `composer-require-checker`.
The only two important commits (imho) are:
- [escape path for php executable, it could contains spaces or quotes ](https://github.com/overtrue/phplint/commit/8b93007177a567e87960d69c872b73cad1b5e8ff).
As both variables `PHP_BINDIR` & `PHP_BINARY` are part of reserved constants I don't think they can be poisoned, in that case the security risk of command line injection is none. The real issue here could be a failed execution.
- [`loadConfiguration` returns `null` if `ParseException` is thown](https://github.com/overtrue/phplint/commit/06f8acd01ef38974803068abf37d385e4ca68e1d)
Feel free to cherry peek or reject.
As always, thanks for your work and project.
=> Minimal improvements

composer.json
The `Symfony\Component\Console\Terminal` class is not available before 3.2.0. This breaks the [builds](https://travis-ci.org/tuupola/ulid/jobs/372634012#L608
) using `--prefer-lowest` switch.  This can also be tested locally from phplint source tree with:
```php
$ composer update --prefer-lowest
$ bin/phplint
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Terminal' not found in /xxx/phplint/src/Command/LintCommand.php:249
```
Setting to `symfony/console` minimum requirement to `^3.2` seems to fix the problem.
=> Make symfony/console 3.2.0 minimal requirement

src/Linter.php
When we use phpcensor|phpci systems there is no ability to use cache feature. 
CI systems create a new temporary directory and build the project. For example 
first commit `/tests/build/24854`
second commit `/tests/build/24855`
File path stored in the cache has a full path. So it is invalid on each build.
p.s. PhpCsFixer uses a relative path to store caches.
=> Use relative file path as the cache key

src/Linter.php
This PR aims to resolve https://github.com/overtrue/phplint/issues/63 by adding the `file_name` key to the error's details.
=> Add file_name to errors details

.gitignore, README.md, composer.json, src/Command/LintCommand.php
Added support for standard JUnit XML reports to be able to use this tool in standard CI/CD environments, and to be able to extract/use the reports easily.
Closes #67
=> JUnit XML output support

.travis.yml, README.md, docker_push.sh
Hi!
Thanks for your great tool!
As I wanted to use it in a CI/CD based on Docker so I had to build and push an image to some registry. It's here https://hub.docker.com/r/gdubicki/overtrue-phplint .
However I would prefer to switch to an image built from your repo, under your name - hence the PR.
Apart from merging this PR you would have to just add your Dockerhub credentials to Travis secrets like documented here https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry .
=> Add building official Dockerhub image

composer.json
When running ci with `$ composer install -prefer-lowest` phplint currently fails with PHP 7.1, 7.2 and 7.3.
```
Warning: proc_open() expects parameter 1 to be string, array given in
/home/travis/build/tuupola/example/vendor/symfony/process/Process.php on line 310
```
This PR fixes the problem by bumping the minimal required version of `symfony/process` to 3.3.
=> Change minimal symfony/process version to 3.3 (fixes #61)

Dockerfile
After [Use multistage build to reduce image size](#81) the image size can be reduced from 400 MB (138 MB compressed) to 76 MB (30 MB compressed) with Alpine linux
=> Use alpine linux to reduce image size

Dockerfile
The docker image is 487 MB (170 MB compressed). With a multistage build the size can be reduced to 400 MB (138 MB compressed).
=> Use multistage build to reduce image size

src/Linter.php, src/Process/Lint.php
This PR makes linting with `warning`  on also find notices and deprecations. 
This could be considered a BC break as the `warning` flag now finds more issues than previously.
=> Allow to lint for deprecations and notices as well

src/Command/LintCommand.php
Hi there!
When using PHPLint in GitLab CI/CD without these changes it'll always fail to complete when ignoring the `allow_failure` flag in `.gitlab-ci.yml`.
Is it at all a good idea to only set the failure code when we're not in quiet mode?
Thanks
Tom
Edit: even when allowing failure(s) in GitLab CI/CD it'll fail to process.
Edit 2: happy to report that my fork, installed via Composer, successfully works in GitLab CI/CD.
=> Allow to silenty fail when --quiet/-q option is used (for use in CI)

README.md
Travis is no longer being used, so switch to the GitHub Actions badge.
=> README.md: replace Travis badge

src/Linter.php
The process callback property is can be accessed before intialisation which causes a fatal error
This PR fixes that. It is also much better typed by using a `Closure` instead of `mixed`, and it sets the property as nullable with null as default.
Finally I changed the no -op function to a short syntax just because its a lot nicer :)
=> Bug fix on process callback

Dockerfile, README.md, entrypoint.sh
As you seems to have not time to do it, here is the same fix I've applied for PHP 8.0, see issue #106 
Fix also the README.md file for Docker cli usage
=> Fix passing arguments and options on Docker image for PHP 7.4

.phplint.yml, src/Command/LintCommand.php, src/Console/Application.php, src/Linter.php
Fix #137
**Note** I've removed bug part of Application version because it will avoid wrong version that we have with current 5.2.2
I've in mind to propose @overtrue a simple way to avoid all changes applied recently
- v5.2.2 : https://github.com/overtrue/phplint/pull/135
- v4.2.1 : https://github.com/overtrue/phplint/pull/134
- v3.1.1 : https://github.com/overtrue/phplint/pull/133
=> fix feature report #137

.phplint.yml, composer.json, src/Command/LintCommand.php, src/Configuration/ConfigResolver.php
=> Introduces new component `ConfigResolver`

docs/usage/console.md
Just a little fix in the documentation.
There was a broken link in the `docs/usage/console.md` to the Configuration.
=> Fix link to Configuration in console.md
